const TOKEN_KEY = 'menu_admin_token';
const API_BASE = '';
let cacheItems = [];
let cacheCats = [];
let cachePayment = [];
let deleteTargetId = null;
const categories = ['BREAKFAST', 'HOT_DRINKS', 'LUNCH_DINNER', 'SNACK', 'BEER', 'TRADITIONAL', 'SOFT_DRINKS'];
const categoryNames = { BREAKFAST: 'Breakfast', HOT_DRINKS: 'Hot Drinks', LUNCH_DINNER: 'Lunch & Dinner', SNACK: 'Snacks & Pizza', BEER: 'Beer', TRADITIONAL: 'Traditional', SOFT_DRINKS: 'Soft Drinks' };

function token() { return localStorage.getItem(TOKEN_KEY); }
function authHeaders(extra = {}) { return { ...extra, ...(token() ? { Authorization: `Bearer ${token()}` } : {}) }; }
async function api(url, options = {}) {
  const headers = options.body instanceof FormData ? authHeaders(options.headers || {}) : authHeaders({ 'Content-Type': 'application/json', ...(options.headers || {}) });
  const response = await fetch(`${API_BASE}${url}`, { ...options, headers });
  const data = await response.json().catch(() => ({}));
  if (response.status === 401) { doLogout(); throw new Error(data.error || 'Session expired'); }
  if (!response.ok) throw new Error(data.error || 'Request failed');
  return data;
}
function esc(value) { return String(value ?? '').replace(/[&<>"']/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[c])); }
function normalize(item) { return { ...item, name_am: item.name_am || item.name || '', name_en: item.name_en || item.name || '', desc_am: item.desc_am || item.description || '', desc_en: item.desc_en || item.description || '', category_key: item.category_key || item.category, img: item.img || item.image_url || '', available: item.available !== false && item.available !== 0 && item.available !== '0' }; }
function showLoginError(message) { const box = document.getElementById('loginError'); const text = document.getElementById('loginErrorText'); if (box && text) { text.textContent = message; box.classList.remove('hidden'); } }
function hideLoginError() { document.getElementById('loginError')?.classList.add('hidden'); }
function togglePwd() { const input = document.getElementById('loginPass'); input.type = input.type === 'password' ? 'text' : 'password'; }
async function doLogin() {
  const username = document.getElementById('loginUser').value.trim();
  const password = document.getElementById('loginPass').value;
  if (!username || !password) return showLoginError('Please enter username and password');
  hideLoginError();
  try { const data = await api('/api/admin/login', { method: 'POST', body: JSON.stringify({ username, password }) }); localStorage.setItem(TOKEN_KEY, data.token); showApp(username); }
  catch (error) { showLoginError(error.message); }
}
function showApp(username) { document.getElementById('loginScreen').style.display = 'none'; document.getElementById('appScreen').style.display = 'flex'; document.getElementById('adminUserLabel').textContent = `Logged in as: ${username}`; loadAll(); }
function handleUnauthorized() { doLogout(); showLoginError('Session expired. Please sign in again.'); }
async function loadAll() { try { const [items, cats, payment] = await Promise.all([api('/api/menu'), api('/api/admin/categories'), api('/api/admin/payment')]); cacheItems = items.map(normalize); cacheCats = cats; cachePayment = payment; renderStats(); renderTable(cacheItems); populateCategorySelect(); renderCatsGrid(); renderPaymentGrid(); } catch (error) { showToast(error.message, true); } }
function renderStats() { const available = cacheItems.filter((item) => item.available).length; document.getElementById('statsRow').innerHTML = [{ label:'Total Items', value:cacheItems.length, icon:'fa-utensils', color:'#f59e0b' }, { label:'Available', value:available, icon:'fa-circle-check', color:'#10b981' }, { label:'Hidden', value:cacheItems.length - available, icon:'fa-eye-slash', color:'#f87171' }, { label:'Categories', value:categories.length, icon:'fa-tags', color:'#283728' }].map((stat) => `<div class="card p-4 flex items-center gap-3"><div style="background:${stat.color}" class="w-10 h-10 rounded-xl flex items-center justify-center text-white"><i class="fa-solid ${stat.icon}"></i></div><div><p class="text-xs text-gray-400">${stat.label}</p><p class="text-xl font-black text-gray-900">${stat.value}</p></div></div>`).join(''); }
function renderTable(items) { const tbody = document.getElementById('itemsTbody'); if (!items.length) { tbody.innerHTML = '<tr><td colspan="6" class="py-12 text-center text-gray-400">No menu items found.</td></tr>'; return; } tbody.innerHTML = items.map((item) => `<tr class="hover:bg-sage-50"><td class="px-4 py-3"><img src="${esc(item.img)}" onerror="this.style.display='none'" alt="" class="w-12 h-12 rounded-xl object-cover"></td><td class="px-4 py-3"><p class="font-bold text-gray-900 text-sm">${esc(item.name_am)}</p><p class="text-xs text-gray-400">${esc(item.name_en)}</p></td><td class="px-4 py-3 hidden sm:table-cell"><span class="bg-sage-100 text-sage-700 text-[11px] font-bold px-2 py-1 rounded-lg">${esc(categoryNames[item.category_key] || item.category_key)}</span></td><td class="px-4 py-3 font-mono font-black">${Number(item.price).toFixed(2)} <span class="text-[10px] text-red-500">ETB</span></td><td class="px-4 py-3"><button onclick="toggleAvail(${item.id})" class="text-[11px] font-bold px-2.5 py-1 rounded-lg ${item.available ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-600'}">${item.available ? 'Available' : 'Hidden'}</button></td><td class="px-4 py-3 text-right"><button onclick="openEditModal(${item.id})" class="bg-sage-100 text-sage-800 text-xs font-bold px-3 py-1.5 rounded-lg">Edit</button> <button onclick="openDeleteModal(${item.id})" class="bg-red-50 text-red-500 text-xs font-bold px-2.5 py-1.5 rounded-lg"><i class="fa-solid fa-trash"></i></button></td></tr>`).join(''); }
function filterTable() { const query = document.getElementById('searchItems').value.toLowerCase(); const category = document.getElementById('filterCat').value; const available = document.getElementById('filterAvail').value; renderTable(cacheItems.filter((item) => (!query || `${item.name_am} ${item.name_en}`.toLowerCase().includes(query)) && (!category || item.category_key === category) && (!available || String(item.available ? 1 : 0) === available))); }
function populateCategorySelect() { const list = cacheCats.length ? cacheCats : categories.map((key) => ({ key, name_en: categoryNames[key] })); const options = list.filter((category) => category.active !== false && category.active !== 0).map((category) => `<option value="${esc(category.key)}">${esc(category.name_en || categoryNames[category.key] || category.key)}</option>`).join(''); document.getElementById('fCategory').innerHTML = options; document.getElementById('filterCat').innerHTML = '<option value="">All Categories</option>' + options; }
function openAddModal() { document.getElementById('modalTitle').textContent = 'Add Menu Item'; document.getElementById('editId').value = ''; ['fNameAm','fNameEn','fDescAm','fDescEn','fTagAm','fTagEn','fImg'].forEach((id) => { document.getElementById(id).value = ''; }); document.getElementById('fPrice').value = ''; document.getElementById('fAvail').checked = true; document.getElementById('itemModal').classList.add('open'); }
function openEditModal(id) { const item = cacheItems.find((entry) => entry.id === id); if (!item) return; document.getElementById('modalTitle').textContent = 'Edit Menu Item'; document.getElementById('editId').value = id; document.getElementById('fNameAm').value = item.name_am; document.getElementById('fNameEn').value = item.name_en; document.getElementById('fDescAm').value = item.desc_am; document.getElementById('fDescEn').value = item.desc_en; document.getElementById('fPrice').value = item.price; document.getElementById('fImg').value = item.img; document.getElementById('fAvail').checked = item.available; document.getElementById('fCategory').value = item.category_key; document.getElementById('itemModal').classList.add('open'); }
function closeItemModal() { document.getElementById('itemModal').classList.remove('open'); }
function previewImg() {}
async function uploadSelectedImage(fileInputId, textInputId) {
  const file = document.getElementById(fileInputId)?.files?.[0];
  if (!file) return showToast('Please choose an image first', true);
  if (!file.type.startsWith('image/') || file.size > 5 * 1024 * 1024) return showToast('Choose an image smaller than 5 MB', true);
  try { const form = new FormData(); form.append('image', file); const data = await api('/api/admin/upload', { method:'POST', body:form }); document.getElementById(textInputId).value = data.url; previewImg(); showToast('Image uploaded'); } catch (error) { showToast(error.message, true); }
}
async function saveItem() {
  const id = document.getElementById('editId').value;
  const nameAm = document.getElementById('fNameAm').value.trim();
  const nameEn = document.getElementById('fNameEn').value.trim();
  const price = Number(document.getElementById('fPrice').value);
  const imageFile = document.getElementById('fImgFile').files[0];
  if (!nameEn || !nameAm || !Number.isFinite(price)) return showToast('Name and valid price are required', true);
  if (imageFile && (imageFile.size > 5 * 1024 * 1024 || !imageFile.type.startsWith('image/'))) return showToast('Choose an image smaller than 5 MB', true);
  const body = new FormData();
  body.append('name', nameEn);
  body.append('name_am', nameAm);
  body.append('name_en', nameEn);
  body.append('category', document.getElementById('fCategory').value);
  body.append('price', price);
  const descAm = document.getElementById('fDescAm').value.trim();
  const descEn = document.getElementById('fDescEn').value.trim();
  body.append('description', descEn || descAm);
  body.append('description_am', descAm);
  body.append('description_en', descEn);
  body.append('is_available', document.getElementById('fAvail').checked);
  body.append('image_url', document.getElementById('fImg').value.trim());
  if (imageFile) body.append('image', imageFile);
  try { await api(id ? `/api/admin/menu/${id}` : '/api/admin/menu', { method: id ? 'PUT' : 'POST', body }); closeItemModal(); showToast(id ? 'Item updated' : 'Item added'); await loadAll(); } catch (error) { showToast(error.message, true); }
}
async function toggleAvail(id) { const item = cacheItems.find((entry) => entry.id === id); if (!item) return; try { await api(`/api/admin/menu/${id}`, { method:'PUT', body:JSON.stringify({ is_available: !item.available }) }); await loadAll(); } catch (error) { showToast(error.message, true); } }
function openDeleteModal(id) { deleteTargetId = id; document.getElementById('deleteModal').classList.add('open'); }
async function confirmDelete() { try { await api(`/api/admin/menu/${deleteTargetId}`, { method:'DELETE' }); document.getElementById('deleteModal').classList.remove('open'); await loadAll(); showToast('Item deleted'); } catch (error) { showToast(error.message, true); } }
function renderCatsGrid() { const cards = cacheCats.map((category) => `<div class="card p-4 space-y-2"><div class="flex justify-between"><div><h3 class="font-black text-sage-900">${esc(category.name_en)}</h3><p class="text-xs text-gray-400">${esc(category.key)}</p></div><div class="flex gap-2"><button onclick="editCategory(${category.id})" class="text-sage-700" title="Edit category"><i class="fa-solid fa-pen-to-square"></i></button><button onclick="deleteCategory(${category.id})" class="text-red-500" title="Delete category"><i class="fa-solid fa-trash"></i></button></div></div><input id="catNameAm_${category.id}" value="${esc(category.name_am)}" placeholder="Amharic name" class="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"><input id="catNameEn_${category.id}" value="${esc(category.name_en)}" placeholder="English name" class="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"><input id="catHero_${category.id}" value="${esc(category.hero_img || '')}" placeholder="/menu-images/food.jpg" class="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"><button onclick="saveCategory(${category.id})" class="w-full bg-sage-800 text-white text-xs font-bold py-2 rounded-xl">Save Category</button></div>`).join(''); document.getElementById('categoriesGrid').innerHTML = `<div class="card p-4 space-y-2"><h3 class="font-black text-sage-900">Add Category</h3><input id="newCatKey" placeholder="Category key" class="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"><input id="newCatNameAm" placeholder="Amharic name" class="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"><input id="newCatNameEn" placeholder="English name" class="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"><button onclick="addCategory()" class="w-full bg-gradient-to-r from-amber-500 to-terracotta-500 text-white text-xs font-bold py-2 rounded-xl">Add Category</button></div>${cards}`; }
function editCategory(id) { document.getElementById(`catNameEn_${id}`)?.focus(); }
async function addCategory() { try { await api('/api/admin/categories', { method:'POST', body:JSON.stringify({ key:document.getElementById('newCatKey').value, name_am:document.getElementById('newCatNameAm').value, name_en:document.getElementById('newCatNameEn').value }) }); await loadAll(); showToast('Category added'); } catch (error) { showToast(error.message, true); } }
async function saveCategory(id) { const category = cacheCats.find((item) => item.id === id); try { await api(`/api/admin/categories/${id}`, { method:'PUT', body:JSON.stringify({ key:category.key, name_am:document.getElementById(`catNameAm_${id}`).value, name_en:document.getElementById(`catNameEn_${id}`).value, icon:category.icon, hero_img:document.getElementById(`catHero_${id}`).value, description_am:category.description_am, description_en:category.description_en, active:true }) }); await loadAll(); showToast('Category updated'); } catch (error) { showToast(error.message, true); } }
async function deleteCategory(id) { if (!confirm('Delete this category?')) return; try { await api(`/api/admin/categories/${id}`, { method:'DELETE' }); await loadAll(); showToast('Category deleted'); } catch (error) { showToast(error.message, true); } }
function renderPaymentGrid() { const cards = cachePayment.map((payment) => `<div class="card p-5 space-y-3"><div class="flex justify-between"><h3 class="font-black text-sage-900">${esc(payment.bank_name)}</h3><div class="flex gap-2"><button onclick="editPayment(${payment.id})" class="text-sage-700" title="Edit payment"><i class="fa-solid fa-pen-to-square"></i></button><button onclick="deletePayment(${payment.id})" class="text-red-500" title="Delete payment"><i class="fa-solid fa-trash"></i></button></div></div><input id="payKey_${payment.id}" value="${esc(payment.bank_key)}" placeholder="Method key" class="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"><input id="payName_${payment.id}" value="${esc(payment.bank_name)}" placeholder="Payment name" class="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"><input id="payHolder_${payment.id}" value="${esc(payment.account_holder || '')}" placeholder="Account holder" class="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"><input id="payNumber_${payment.id}" value="${esc(payment.account_number || '')}" placeholder="Account number / phone" class="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"><button onclick="savePayment(${payment.id})" class="w-full bg-sage-800 text-white text-xs font-bold py-2.5 rounded-xl">Save Payment Info</button></div>`).join(''); document.getElementById('paymentGrid').innerHTML = `<div class="card p-5 space-y-3"><h3 class="font-black text-sage-900">Add Payment Method</h3><input id="newPayKey" placeholder="Method key" class="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"><input id="newPayName" placeholder="Payment name" class="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"><input id="newPayHolder" placeholder="Account holder" class="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"><input id="newPayNumber" placeholder="Account number / phone" class="w-full border border-gray-200 rounded-xl px-3 py-2 text-sm"><button onclick="addPayment()" class="w-full bg-gradient-to-r from-amber-500 to-terracotta-500 text-white text-xs font-bold py-2.5 rounded-xl">Add Payment Method</button></div>${cards}`; }
function editPayment(id) { document.getElementById(`payName_${id}`)?.focus(); }
async function addPayment() { try { await api('/api/admin/payment', { method:'POST', body:JSON.stringify({ bank_key:document.getElementById('newPayKey').value, bank_name:document.getElementById('newPayName').value, account_holder:document.getElementById('newPayHolder').value, account_number:document.getElementById('newPayNumber').value }) }); await loadAll(); showToast('Payment method added'); } catch (error) { showToast(error.message, true); } }
async function savePayment(id) { const payment = cachePayment.find((item) => item.id === id); try { await api(`/api/admin/payment/${id}`, { method:'PUT', body:JSON.stringify({ bank_key:document.getElementById(`payKey_${id}`).value, bank_name:document.getElementById(`payName_${id}`).value, account_holder:document.getElementById(`payHolder_${id}`).value, account_number:document.getElementById(`payNumber_${id}`).value, dial_code:payment.dial_code, instructions_am:payment.instructions_am, instructions_en:payment.instructions_en, color:payment.color, active:true }) }); await loadAll(); showToast('Payment updated'); } catch (error) { showToast(error.message, true); } }
async function deletePayment(id) { if (!confirm('Delete this payment method?')) return; try { await api(`/api/admin/payment/${id}`, { method:'DELETE' }); await loadAll(); showToast('Payment deleted'); } catch (error) { showToast(error.message, true); } }
async function changePassword() { const currentPassword = document.getElementById('oldPass').value; const newPassword = document.getElementById('newPass').value; const confirmPassword = document.getElementById('confirmPass').value; if (!currentPassword || newPassword.length < 8 || newPassword !== confirmPassword) return showToast('Use matching passwords of at least 8 characters', true); try { await api('/api/admin/change-password', { method:'PUT', body:JSON.stringify({ oldPassword:currentPassword, newPassword }) }); document.getElementById('oldPass').value=''; document.getElementById('newPass').value=''; document.getElementById('confirmPass').value=''; showToast('Password updated'); } catch (error) { showToast(error.message, true); } }
function togglePassword(fieldId, button) { const field = document.getElementById(fieldId); const visible = field.type === 'text'; field.type = visible ? 'password' : 'text'; button.querySelector('i').className = visible ? 'fa-solid fa-eye' : 'fa-solid fa-eye-slash'; }
function switchTab(name) { document.querySelectorAll('.tab-pane').forEach((pane) => pane.classList.remove('active')); document.querySelectorAll('.tab-btn').forEach((button) => button.classList.remove('active')); document.getElementById(`tab-${name}`)?.classList.add('active'); document.getElementById(`tab-${name}-btn`)?.classList.add('active'); if (name === 'categories') renderCatsGrid(); if (name === 'payment') renderPaymentGrid(); }
function showToast(message, isError = false) { const toast = document.getElementById('toast'); document.getElementById('toastMsg').textContent = message; document.getElementById('toastIcon').style.color = isError ? '#f87171' : '#34d399'; toast.style.display = 'flex'; clearTimeout(toast._timer); toast._timer = setTimeout(() => { toast.style.display = 'none'; }, 3000); }
function doLogout() { localStorage.removeItem(TOKEN_KEY); document.getElementById('appScreen').style.display = 'none'; document.getElementById('loginScreen').style.display = 'flex'; }

window.addEventListener('DOMContentLoaded', () => { populateCategorySelect(); if (token()) { showApp('admin'); } });
